/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentSelectSubjectRouteImport } from './routes/student/select-subject'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as StudentresultRouteRouteImport } from './routes/student/(result)/route'
import { Route as StudentexamRouteRouteImport } from './routes/student/(exam)/route'
import { Route as StudentauthRouteRouteImport } from './routes/student/(auth)/route'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/dashboard/route'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as StudentresultSubjectResultRouteImport } from './routes/student/(result)/subject-result'
import { Route as StudentresultOverallResultRouteImport } from './routes/student/(result)/overall-result'
import { Route as StudentexamExamQuestionsDemoRouteImport } from './routes/student/(exam)/exam-questions-demo'
import { Route as StudentexamExamQuestionsRouteImport } from './routes/student/(exam)/exam-questions'
import { Route as StudentauthLoginRouteImport } from './routes/student/(auth)/login'
import { Route as AdminDashboardStudentsRouteImport } from './routes/admin/dashboard/students'
import { Route as AdminDashboardSettingsRouteImport } from './routes/admin/dashboard/settings'
import { Route as AdminDashboardResultsRouteImport } from './routes/admin/dashboard/results'
import { Route as AdminDashboardQuestionsRouteImport } from './routes/admin/dashboard/questions'
import { Route as AdminDashboardExamsRouteImport } from './routes/admin/dashboard/exams'
import { Route as StudentauthPostsPostIdRouteImport } from './routes/student/(auth)/posts.$postId'

const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSelectSubjectRoute = StudentSelectSubjectRouteImport.update({
  id: '/select-subject',
  path: '/select-subject',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentresultRouteRoute = StudentresultRouteRouteImport.update({
  id: '/(result)',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentexamRouteRoute = StudentexamRouteRouteImport.update({
  id: '/(exam)',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentauthRouteRoute = StudentauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const StudentresultSubjectResultRoute =
  StudentresultSubjectResultRouteImport.update({
    id: '/subject-result',
    path: '/subject-result',
    getParentRoute: () => StudentresultRouteRoute,
  } as any)
const StudentresultOverallResultRoute =
  StudentresultOverallResultRouteImport.update({
    id: '/overall-result',
    path: '/overall-result',
    getParentRoute: () => StudentresultRouteRoute,
  } as any)
const StudentexamExamQuestionsDemoRoute =
  StudentexamExamQuestionsDemoRouteImport.update({
    id: '/exam-questions-demo',
    path: '/exam-questions-demo',
    getParentRoute: () => StudentexamRouteRoute,
  } as any)
const StudentexamExamQuestionsRoute =
  StudentexamExamQuestionsRouteImport.update({
    id: '/exam-questions',
    path: '/exam-questions',
    getParentRoute: () => StudentexamRouteRoute,
  } as any)
const StudentauthLoginRoute = StudentauthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StudentauthRouteRoute,
} as any)
const AdminDashboardStudentsRoute = AdminDashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardResultsRoute = AdminDashboardResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardQuestionsRoute = AdminDashboardQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardExamsRoute = AdminDashboardExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const StudentauthPostsPostIdRoute = StudentauthPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => StudentauthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentresultRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/student/select-subject': typeof StudentSelectSubjectRoute
  '/admin/dashboard/exams': typeof AdminDashboardExamsRoute
  '/admin/dashboard/questions': typeof AdminDashboardQuestionsRoute
  '/admin/dashboard/results': typeof AdminDashboardResultsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/students': typeof AdminDashboardStudentsRoute
  '/student/login': typeof StudentauthLoginRoute
  '/student/exam-questions': typeof StudentexamExamQuestionsRoute
  '/student/exam-questions-demo': typeof StudentexamExamQuestionsDemoRoute
  '/student/overall-result': typeof StudentresultOverallResultRoute
  '/student/subject-result': typeof StudentresultSubjectResultRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/student/posts/$postId': typeof StudentauthPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentresultRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/student/select-subject': typeof StudentSelectSubjectRoute
  '/admin/dashboard/exams': typeof AdminDashboardExamsRoute
  '/admin/dashboard/questions': typeof AdminDashboardQuestionsRoute
  '/admin/dashboard/results': typeof AdminDashboardResultsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/students': typeof AdminDashboardStudentsRoute
  '/student/login': typeof StudentauthLoginRoute
  '/student/exam-questions': typeof StudentexamExamQuestionsRoute
  '/student/exam-questions-demo': typeof StudentexamExamQuestionsDemoRoute
  '/student/overall-result': typeof StudentresultOverallResultRoute
  '/student/subject-result': typeof StudentresultSubjectResultRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/student/posts/$postId': typeof StudentauthPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/student/(auth)': typeof StudentauthRouteRouteWithChildren
  '/student/(exam)': typeof StudentexamRouteRouteWithChildren
  '/student/(result)': typeof StudentresultRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/student/select-subject': typeof StudentSelectSubjectRoute
  '/admin/dashboard/exams': typeof AdminDashboardExamsRoute
  '/admin/dashboard/questions': typeof AdminDashboardQuestionsRoute
  '/admin/dashboard/results': typeof AdminDashboardResultsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/students': typeof AdminDashboardStudentsRoute
  '/student/(auth)/login': typeof StudentauthLoginRoute
  '/student/(exam)/exam-questions': typeof StudentexamExamQuestionsRoute
  '/student/(exam)/exam-questions-demo': typeof StudentexamExamQuestionsDemoRoute
  '/student/(result)/overall-result': typeof StudentresultOverallResultRoute
  '/student/(result)/subject-result': typeof StudentresultSubjectResultRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/student/(auth)/posts/$postId': typeof StudentauthPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reset-password'
    | '/student/select-subject'
    | '/admin/dashboard/exams'
    | '/admin/dashboard/questions'
    | '/admin/dashboard/results'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/students'
    | '/student/login'
    | '/student/exam-questions'
    | '/student/exam-questions-demo'
    | '/student/overall-result'
    | '/student/subject-result'
    | '/admin/dashboard/'
    | '/student/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/student'
    | '/admin/login'
    | '/admin/reset-password'
    | '/student/select-subject'
    | '/admin/dashboard/exams'
    | '/admin/dashboard/questions'
    | '/admin/dashboard/results'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/students'
    | '/student/login'
    | '/student/exam-questions'
    | '/student/exam-questions-demo'
    | '/student/overall-result'
    | '/student/subject-result'
    | '/admin/dashboard'
    | '/student/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/admin/dashboard'
    | '/student/(auth)'
    | '/student/(exam)'
    | '/student/(result)'
    | '/admin/login'
    | '/admin/reset-password'
    | '/student/select-subject'
    | '/admin/dashboard/exams'
    | '/admin/dashboard/questions'
    | '/admin/dashboard/results'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/students'
    | '/student/(auth)/login'
    | '/student/(exam)/exam-questions'
    | '/student/(exam)/exam-questions-demo'
    | '/student/(result)/overall-result'
    | '/student/(result)/subject-result'
    | '/admin/dashboard/'
    | '/student/(auth)/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/select-subject': {
      id: '/student/select-subject'
      path: '/select-subject'
      fullPath: '/student/select-subject'
      preLoaderRoute: typeof StudentSelectSubjectRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/student/(result)': {
      id: '/student/(result)'
      path: ''
      fullPath: '/student'
      preLoaderRoute: typeof StudentresultRouteRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/(exam)': {
      id: '/student/(exam)'
      path: ''
      fullPath: '/student'
      preLoaderRoute: typeof StudentexamRouteRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/(auth)': {
      id: '/student/(auth)'
      path: ''
      fullPath: '/student'
      preLoaderRoute: typeof StudentauthRouteRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/student/(result)/subject-result': {
      id: '/student/(result)/subject-result'
      path: '/subject-result'
      fullPath: '/student/subject-result'
      preLoaderRoute: typeof StudentresultSubjectResultRouteImport
      parentRoute: typeof StudentresultRouteRoute
    }
    '/student/(result)/overall-result': {
      id: '/student/(result)/overall-result'
      path: '/overall-result'
      fullPath: '/student/overall-result'
      preLoaderRoute: typeof StudentresultOverallResultRouteImport
      parentRoute: typeof StudentresultRouteRoute
    }
    '/student/(exam)/exam-questions-demo': {
      id: '/student/(exam)/exam-questions-demo'
      path: '/exam-questions-demo'
      fullPath: '/student/exam-questions-demo'
      preLoaderRoute: typeof StudentexamExamQuestionsDemoRouteImport
      parentRoute: typeof StudentexamRouteRoute
    }
    '/student/(exam)/exam-questions': {
      id: '/student/(exam)/exam-questions'
      path: '/exam-questions'
      fullPath: '/student/exam-questions'
      preLoaderRoute: typeof StudentexamExamQuestionsRouteImport
      parentRoute: typeof StudentexamRouteRoute
    }
    '/student/(auth)/login': {
      id: '/student/(auth)/login'
      path: '/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentauthLoginRouteImport
      parentRoute: typeof StudentauthRouteRoute
    }
    '/admin/dashboard/students': {
      id: '/admin/dashboard/students'
      path: '/students'
      fullPath: '/admin/dashboard/students'
      preLoaderRoute: typeof AdminDashboardStudentsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/settings': {
      id: '/admin/dashboard/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/results': {
      id: '/admin/dashboard/results'
      path: '/results'
      fullPath: '/admin/dashboard/results'
      preLoaderRoute: typeof AdminDashboardResultsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/questions': {
      id: '/admin/dashboard/questions'
      path: '/questions'
      fullPath: '/admin/dashboard/questions'
      preLoaderRoute: typeof AdminDashboardQuestionsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/exams': {
      id: '/admin/dashboard/exams'
      path: '/exams'
      fullPath: '/admin/dashboard/exams'
      preLoaderRoute: typeof AdminDashboardExamsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/student/(auth)/posts/$postId': {
      id: '/student/(auth)/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/student/posts/$postId'
      preLoaderRoute: typeof StudentauthPostsPostIdRouteImport
      parentRoute: typeof StudentauthRouteRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardExamsRoute: typeof AdminDashboardExamsRoute
  AdminDashboardQuestionsRoute: typeof AdminDashboardQuestionsRoute
  AdminDashboardResultsRoute: typeof AdminDashboardResultsRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardStudentsRoute: typeof AdminDashboardStudentsRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardExamsRoute: AdminDashboardExamsRoute,
  AdminDashboardQuestionsRoute: AdminDashboardQuestionsRoute,
  AdminDashboardResultsRoute: AdminDashboardResultsRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardStudentsRoute: AdminDashboardStudentsRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentauthRouteRouteChildren {
  StudentauthLoginRoute: typeof StudentauthLoginRoute
  StudentauthPostsPostIdRoute: typeof StudentauthPostsPostIdRoute
}

const StudentauthRouteRouteChildren: StudentauthRouteRouteChildren = {
  StudentauthLoginRoute: StudentauthLoginRoute,
  StudentauthPostsPostIdRoute: StudentauthPostsPostIdRoute,
}

const StudentauthRouteRouteWithChildren =
  StudentauthRouteRoute._addFileChildren(StudentauthRouteRouteChildren)

interface StudentexamRouteRouteChildren {
  StudentexamExamQuestionsRoute: typeof StudentexamExamQuestionsRoute
  StudentexamExamQuestionsDemoRoute: typeof StudentexamExamQuestionsDemoRoute
}

const StudentexamRouteRouteChildren: StudentexamRouteRouteChildren = {
  StudentexamExamQuestionsRoute: StudentexamExamQuestionsRoute,
  StudentexamExamQuestionsDemoRoute: StudentexamExamQuestionsDemoRoute,
}

const StudentexamRouteRouteWithChildren =
  StudentexamRouteRoute._addFileChildren(StudentexamRouteRouteChildren)

interface StudentresultRouteRouteChildren {
  StudentresultOverallResultRoute: typeof StudentresultOverallResultRoute
  StudentresultSubjectResultRoute: typeof StudentresultSubjectResultRoute
}

const StudentresultRouteRouteChildren: StudentresultRouteRouteChildren = {
  StudentresultOverallResultRoute: StudentresultOverallResultRoute,
  StudentresultSubjectResultRoute: StudentresultSubjectResultRoute,
}

const StudentresultRouteRouteWithChildren =
  StudentresultRouteRoute._addFileChildren(StudentresultRouteRouteChildren)

interface StudentRouteRouteChildren {
  StudentauthRouteRoute: typeof StudentauthRouteRouteWithChildren
  StudentexamRouteRoute: typeof StudentexamRouteRouteWithChildren
  StudentresultRouteRoute: typeof StudentresultRouteRouteWithChildren
  StudentSelectSubjectRoute: typeof StudentSelectSubjectRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentauthRouteRoute: StudentauthRouteRouteWithChildren,
  StudentexamRouteRoute: StudentexamRouteRouteWithChildren,
  StudentresultRouteRoute: StudentresultRouteRouteWithChildren,
  StudentSelectSubjectRoute: StudentSelectSubjectRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
